export let result = {
     "res":{
        "defaultMenu":{
            "id":0,
            "label":"默认导出项",
            "children":[{
                "id":1,
                "label":"企业（单位）编号",
                "name":"qybh",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":2,
                "label":"企业（单位）名称",
                "name":"qymz",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":3,
                "label":"注册地",
                "name":"zcd",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":4,
                "label":"统一社会信用代码",
                "name":"tyshxydm",
                "ischecked":true,
                "isDisabled":true
            }]
        }, 
        "optionalMenu":
        [{
            "id":5,
            "label":"委托信息",
            "ischecked":false,
            "isDisabled":false,
            "children":[{
                "id":6,
                "label":"委托代理人",
                "name":"wtdkr",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":7,
                "label":"联系电话",
                "name":"lxdh",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":8,
                "label":"证件类型",
                "name":"zjlx",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":9,
                "label":"证件号码",
                "name":"zjhm",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":10,
                "label":"号码",
                "name":"hm",
                "ischecked":true,
                "isDisabled":true
            }]
        },{
            "id":11,
            "label":"企业信息",
            "ischecked":false,
            "isDisabled":false,
            "children":[{
                "id":12,
                "label":"企业简称",
                "name":"qyjz",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":13,
                "label":"母公司",
                "name":"mgs",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":14,
                "label":"企业类型",
                "name":"qylx",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":15,
                "label":"负责人",
                "name":"fzr",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":16,
                "label":"负责人联系电话",
                "name":"fzrlxdh",
                "ischecked":true,
                "isDisabled":true
            },{
                "id":17,
                "label":"项目所在区域",
                "name":"xmszqy",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":18,
                "label":"银行类型",
                "name":"yhlx",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":19,
                "label":"电子邮箱",
                "name":"dzyx",
                "ischecked":true,
                "isDisabled":true
            },
            {
                "id":20,
                "label":"企业网址",
                "name":"qywz",
                "ischecked":true,
                "isDisabled":true
            }]
        }]
     }
 }
 